import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import SideBar from "@/components/main/SideBar";
import NavBar from "@/components/main/NavBar";
import { ThemeProvider } from "next-themes";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
        <SidebarProvider>
            <div className="flex min-h-screen w-full">
              <SideBar />

              <div className="flex flex-1 flex-col">
                <header className="sticky top-0 z-40 bg-card/80 backdrop-blur-sm border-b border-border">
           <NavBar />
            <div className="flex items-center gap-4 px-4 py-2">
              <SidebarTrigger className="lg:hidden" />
            </div>

                </header>

                <main className="">
                  <div className="container mx-auto px-4 py-6">{children}
                            <ToastContainer position="top-right" autoClose={3000} />

                  </div>
                </main>

              
              </div>
            </div>
          </SidebarProvider>
             </ThemeProvider>
      </body>
    </html>
  );
}
